python3 /home/mila/d/diganta.misra/projects/ILM-VP/experiments/cnn/ilm_vp.py \
        --network LT \
        --n_shot 1 \
        --batch_size 8 \
        --dataset cifar10 \
        --pretrained_dir /home/mila/d/diganta.misra/scratch/ImageNetCheckpoint \
        --results_path /home/mila/d/diganta.misra/scratch/vp_results \
        --sparsity 9 \
        --seed 1 \
        --train_data_fraction 0.5 \
        --wandb \
        --run_name ilm_vp \